workflows:
  linux-system-check:
    name: CPU Info Workflow
    max_build_duration: 10
    instance_type: linux_x4 # Corrected from linux_x86_64
    scripts:
      - name: Display CPU Architecture
        script: |
          echo "Listing CPU details:"
          lscpu
      - name: Check Available Processors
        script: |
          echo "Number of processing units available:"
          nproc
