workflows:
  mac-cpp-build:
    name: C++ Build & Run (Mac M4)
    max_build_duration: 10
    instance_type: mac_mini_m4   # adjust if your CI provider uses a different name

    scripts:
      - name: Show System Info
        script: |
          echo "CPU Architecture:"
          uname -m
          echo "CPU Cores:"
          sysctl -n hw.ncpu

      - name: Build and Run C++ Program
        script: |
          echo "Compiling..."
          clang++ -std=c++14 -O3 -march=native lmao.cpp -o soul -pthread

          echo "Making executable..."
          chmod +x soul

          echo "Running..."
          ./soul 195.154.218.179 80 60 200
